// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwveiVyT6h4CpZUEgNc2ThW0kXiPXA6Jg',
    appId: '1:326074345757:web:b0657159ff4e04d99c19f4',
    messagingSenderId: '326074345757',
    projectId: 'floaid-fd7ad',
    authDomain: 'floaid-fd7ad.firebaseapp.com',
    databaseURL: 'https://floaid-fd7ad-default-rtdb.firebaseio.com',
    storageBucket: 'floaid-fd7ad.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4MK5lGfjtFBfQycdaF7ESjhBGQ391nrM',
    appId: '1:326074345757:android:8ba9f73c4eff89d49c19f4',
    messagingSenderId: '326074345757',
    projectId: 'floaid-fd7ad',
    databaseURL: 'https://floaid-fd7ad-default-rtdb.firebaseio.com',
    storageBucket: 'floaid-fd7ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChYkc2zkqcTLyntzyPHaCGjYcnQ1lPoNA',
    appId: '1:326074345757:ios:e024974aaabdc4089c19f4',
    messagingSenderId: '326074345757',
    projectId: 'floaid-fd7ad',
    databaseURL: 'https://floaid-fd7ad-default-rtdb.firebaseio.com',
    storageBucket: 'floaid-fd7ad.firebasestorage.app',
    iosClientId: '326074345757-9p76e9lpb5n6mt3a5b1qioe45p8g28n6.apps.googleusercontent.com',
    iosBundleId: 'com.example.flooAidRewrite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChYkc2zkqcTLyntzyPHaCGjYcnQ1lPoNA',
    appId: '1:326074345757:ios:e024974aaabdc4089c19f4',
    messagingSenderId: '326074345757',
    projectId: 'floaid-fd7ad',
    databaseURL: 'https://floaid-fd7ad-default-rtdb.firebaseio.com',
    storageBucket: 'floaid-fd7ad.firebasestorage.app',
    iosClientId: '326074345757-9p76e9lpb5n6mt3a5b1qioe45p8g28n6.apps.googleusercontent.com',
    iosBundleId: 'com.example.flooAidRewrite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwveiVyT6h4CpZUEgNc2ThW0kXiPXA6Jg',
    appId: '1:326074345757:web:7d5367c111b661109c19f4',
    messagingSenderId: '326074345757',
    projectId: 'floaid-fd7ad',
    authDomain: 'floaid-fd7ad.firebaseapp.com',
    databaseURL: 'https://floaid-fd7ad-default-rtdb.firebaseio.com',
    storageBucket: 'floaid-fd7ad.firebasestorage.app',
  );
}
